CREATE OR REPLACE TRIGGER AFTERINSERTBOOK
AFTER INSERT ON BOOK FOR EACH ROW
DECLARE
AVERAGE NUMBER;
BEGIN
INSERT INTO BOOK_LOG
VALUES(:NEW.BOOKID, :NEW.BOOKNAME, :NEW.PUBLISHER, :NEW.PRICE);
DBMS_OUTPUT.PUT_LINE('삽입 투플을 BOOK_LOG 테이블에 백업..');
END;
/

INSERT INTO BOOK VALUES(14, '스포츠 과학 1', '이상미디어', 25000);
SELECT * FROM BOOK WHERE BOOKID='14';
SELECT * FROM BOOK_LOG WHERE BOOKID_L='14';