CREATE OR REPLACE FUNCTION FNC_INTEREST(
PRICE NUMBER) RETURN INT
IS
MYINTEREST NUMBER;
BEGIN
IF PRICE >=30000 THEN MYINTEREST := PRICE * 0.1;
ELSE MYINTEREST := PRICE * 0.05;
END IF;
RETURN MYINTEREST;
END;
/

SELECT CUSTID, ORDERID, SALEPRICE, FNC_INTEREST(SALEPRICE) INTEREST
FROM ORDERS;