CREATE OR REPLACE PROCEDURE INSERTBOOK (
MYBOOKID IN NUMBER, 
MYBOOKNAME IN VARCHAR2, 
MYPUBLISHER IN VARCHAR2, 
MYPRICE IN NUMBER)
AS 
BEGIN
INSERT INTO BOOK(BOOKID, BOOKNAME, PUBLISHER, PRICE) 
VALUES(MYBOOKID, MYBOOKNAME, MYPUBLISHER, MYPRICE);
END;
/

EXEC INSERTBOOK(13, '스포츠과학', '마당과학서적', 25000);
SELECT * FROM BOOK;