INSERT INTO SUMMER VALUES (100, 'FORTRAN', 20000);
INSERT INTO SUMMER VALUES (150, 'PASCAL', 15000);
INSERT INTO SUMMER VALUES (200, 'C', 10000);
INSERT INTO SUMMER VALUES (250, 'FORTRAN', 20000);

SELECT PRICE "C 수강료" FROM SUMMER WHERE CLASS='C';

DELETE FROM SUMMER WHERE SID=200;

INSERT INTO SUMMER VALUES (NULL, 'JAVA', 25000);

SELECT * FROM SUMMER;

SELECT COUNT(*) "수강인원" FROM SUMMER;

SELECT COUNT(SID) "수강인원" FROM SUMMER;

UPDATE SUMMER SET PRICE=15000 WHERE CLASS='FORTRAN';

SELECT * FROM SUMMER;

SELECT DISTINCT PRICE "FORTRAN 수강료" FROM SUMMER WHERE CLASS='FORTRAN';

UPDATE SUMMER SET PRICE=20000 WHERE CLASS='FORTRAN';

DELETE FROM SUMMER WHERE SID IS NULL;

CREATE TABLE SUMMERPRICE(
CLASS VARCHAR(20),
PRICE INTEGER);

INSERT INTO SUMMERPRICE VALUES ('FORTRAN', 20000);
INSERT INTO SUMMERPRICE VALUES ('PASCAL', 15000);
INSERT INTO SUMMERPRICE VALUES ('C', 10000);

SELECT * FROM SUMMERPRICE;

CREATE TABLE SUMMERENROLL(
SID INTEGER,
CLASS VARCHAR(20));

SELECT * FROM SUMMERENROLL;

SELECT PRICE "C 수강료" FROM SUMMERPRICE WHERE CLASS='C';

DELETE FROM SUMMERENROLL WHERE SID=200;

SELECT * FROM SUMMERENROLL;

UPDATE SUMMERPRICE SET PRICE=15000 WHERE CLASS='FORTRAN';

SELECT PRICE "FORTRAN 수강료" FROM SUMMERPRICE WHERE CLASS='FORTRAN';

