CREATE TABLESPACE MD_TBS DATAFILE 'C:\MADANG\ORADATA\MD_TBS_DATA01.DBF' SIZE 10M;

CREATE TABLESPACE MD_TEST DATAFILE 'C:\MADANG\ORADATA\MD_TEST_DATA01.DBF' SIZE 10M;

DROP TABLESPACE MD_TEST INCLUDING CONTENTS AND DATAFILES;

CREATE USER MDGUEST IDENTIFIED BY MDGUEST;

CREATE USER MDGUEST2 IDENTIFIED BY MDGUEST2 DEFAULT TABLESPACE MD_TBS;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO MDGUEST;
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO MDGUEST2;

SELECT * FROM BOOK;

SELECT * FROM MADANG.BOOK;

GRANT SELECT ON BOOK TO MDGUEST;

GRANT SELECT, UPDATE ON CUSTOMER TO MDGUESTWITH GRANT OPTION;

GRANT SELECT ON MADANG.BOOK TO MDGUEST2;

GRANT SELECT ON MADANG.CUSTOMER TO MDGUEST2;

GRANT SELECT ON ORDERS TO PUBLIC;

REVOKE SELECT ON BOOK FROM MDGUEST;

REVOKE SELECT ON CUSTOMER FROM MDGUEST;

GRANT CREATE ANY TABLE, CREATE ANY VIEW TO PROGRAMMER;

GRANT PROGRAMMER TO MDGUEST;

SET ROLE ALL;

CREATE TABLE MDGUEST2.NEWTABLE(
MYNAME VARCHAR2(40),
MYPHONE VARCHAR2(20));

INSERT INTO MDGUEST2.NEWTABLE(MYNAME, MYPHONE) VALUES ('ȫ�浿', '000-000-0100');

