SELECT SYS_CONTEXT('USERENV','SESSIONID') FROM DUAL;

SET TRANSACTION NAME 'T2';

SELECT * FROM BOOK WHERE BOOKID = 1;

UPDATE BOOK SET PRICE = PRICE +100 WHERE BOOKID = 1;

COMMIT;

UPDATE BOOK SET PRICE = PRICE * 1.1 WHERE BOOKID = 2;

UPDATE BOOK SET PRICE = PRICE * 1.1 WHERE BOOKID = 1;

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

UPDATE USERS SET AGE = 21 WHERE ID = 1;

SELECT * FROM USERS WHERE ID = 1;

ROLLBACK;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

UPDATE USERS SET AGE = 21 WHERE ID = 1;

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

INSERT INTO USERS VALUES (3, 'BOb', 27);

COMMIT;

SELECT * FROM USERS WHERE AGE BETWEEN 10 AND 30;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT SUM(PRICE) 총액 FROM BOOK;

UPDATE BOOK SET PRICE = PRICE+500 WHERE BOOKID = 1;

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT SUM(PRICE) CHDDOR FROM BOOK;

INSERT INTO BOOK VALUES (11, '테스트', '테스트출판사', 5500);

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT SUM(PRICE) 총액 FROM BOOK;

INSERT INTO BOOK VALUES (12, '테스트', '테스트출판사', 5500);

SELECT SUM(PRICE) 총액 FROM BOOK;

COMMIT;