SET TRANSACTION NAME 'T1';

SELECT * FROM BOOK WHERE BOOKID=1;

UPDATE BOOK SET PRICE = 7100 WHERE BOOKID=1;

COMMIT;

SELECT SYS_CONTEXT('USERENV','SESSIONID') FROM DUAL;

UPDATE BOOK SET PRICE= PRICE +100 WHERE BOOKID = 1;

UPDATE BOOK SET PRICE= PRICE +100 WHERE BOOKID = 2;

COMMIT;

CREATE TABLE USERS (
ID NUMBER, NMAE VARCHAR(20), AGE NUMBER);

INSERT INTO USERS VALUES (1, 'HONG GILDONG', 30);

SELECT * FROM USERS;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT * FROM USERS WHERE ID = 1;

SELECT * FROM USERS WHERE ID = 1;

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT * FROM USERS WHERE ID = 1;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT * FROM USERS WHERE AGE BETWEEN 10 AND 30;

COMMIT;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

SELECT SUM(PRICE) รัพื FROM BOOK;

COMMIT;

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

SELECT SUM(PRICE) รัพื FROM BOOK;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SELECT SUM(PRICE) รัพื FROM BOOK;

COMMIT;

